 name: CI

 on:
   workflow_dispatch:

 jobs:
   build:

     runs-on: ubuntu-latest
     env:
       MY_ENV_VAR: "Hello, Environment variable"
     steps:
     - uses: actions/checkout@v2
     - name: Access Environment variables
       run: echo $MY_ENV_VAR
     - name: Access Secret
       run: echo ${{ secrets.PASSWORD }}
